// List<String> ftpSites = [
//   'http://showtimebd.com',
//   'http://circleftp.net',
//   'http://google.com',
//   'http://quetelbd.net/',
//   'http://discoveryftp.net/',
//   'http://movies.discoveryftp.net/',
//   'http://ftpbd.net/',
//   'http://media.ftpbd.net/',
//   'http://server1.ftpbd.net/',
//   'http://server4.ftpbd.net/',
//   'http://www.naturalbd.com/',
//   'http://new.naturalbd.com/',
//   'http://dhakamovie.com/',
//   'http://ctgmovies.com/',
//   'http://crazyctg.com/',
//   'http://www.ctgflix.com/',
//   'http://media.ctgfun.com/',
//   'http://www.ctghall.com/',
//   'http://www.ctgstream.com/',
//   'http://ctghub.com/',
//   'http://www.cinehub24.com/',
//   'http://moviehaat.net/',
//   'http://fs.ebox.live/',
//   'http://fileserver.ebox.live/',
//   'http://pollyflix.com/',
//   'http://fs.amrbd.com/',
//   'http://fs2.amrbd.com/',
// ];
var ftpSites = [
  'http://circleftp.net/',
  'http://bongobd.com/',
  'http://showtimebd.com/',
  'http://patalpuri.com/',
  'http://172.16.50.4/',
  'http://roarmediazone.com/',
  'http://172.16.50.5/',
  'http://172.16.50.5/',
  'http://netathomebd.com/',
  'http://mangogamers.com/',
  'http://ftpbd.net/',
  'http://103.58.73.9/',
  'http://media.ftpbd.net/',
  'http://server1.ftpbd.net/',
  'http://server4.ftpbd.net/',
  'http://alphamediazone.com/moviedom/allmovies.php',
  'http://162.12.215.254/',
  'http://naturalbd.com/',
  'http://crazyctg.com/',
  'http://mybdplex.com/',
  'http://elaach.com/',
  'http://vdomela.com/',
  'http://103.119.100.54/',
  'http://anthousebd.net/',
  'http://dhakaftp.com/',
  'http://ftpbd.com/',
  'http://media.netmatrixbd.com/',
  'http://quickonlineftp.com/',
  'http://khulnaplex.net/',
  'http://fs.ebox.live/',
  'http://cdn1.bossbd.net/',
  'http://cdn2.bossbd.net/',
  'http://dhakamovie.com/',
  'http://ftp.bossbd.server/',
  'http://103.204.244.70/',
  'http://kissanime.ru/',
  'http://funtimebd.com/',
  'http://mojarftp.com/',
  'http://movieboxbd.com/',
  'http://bdlan.net/',
  'http://ctghall.com/',
  'http://media.dfnbd.net/',
  'http://103.70.140.14/',
  'http://45.120.114.222/',
  'http://live.moviebazar.net/',
  'http://starflixbd.com/',
  'http://radio.net.bd/',
  'http://ihub.live/',
  'http://103.195.1.50/allmovies.php?page=1&entries=64&sort=DESC&w=grid',
  'http://pandaclubbd.com/',
  'http://evonetbd.com/',
  'http://202.83.124.242:32400/web/index.html#',
  'http://ado.dfnbd.net/index?a=explore',
  'http://movies.discoveryftp.net/',
  'http://cdn1.discoveryftp.net/',
  'http://cdn2.discoveryftp.net/',
  'http://cdn3.discoveryftp.net/',
  'http://172.27.27.84/',
  'http://172.27.27.83/',
  'http://103.58.73.9/',
  'http://server4.ftpbd.net/',
  'http://server1.ftpbd.net/',
  'http://media.ftpbd.net/',
  'http://cinehub24.com/',
  'http://moviehaat.net/',
  'http://fs2.amrbd.com/',
  'http://pollyflix.com/',
  'http://fs.amrbd.com/',
  'http://12.1.1.3/flix',
  'http://12.1.1.2/',
  'http://103.3.226.208/',
  'http://freedownloadbd.com/',
  'http://172.22.22.100/',
  'http://172.22.22.101/',
  'http://nagordola.com.bd/',
  'http://asianftp.com/',
  'http://fs1.dflix.live/',
  'http://dflix.live/',
  'http://103.102.27.170/',
  'http://bitflixbd.com/',
  'http://172.16.16.5/',
  'http://172.16.16.3/',
  'http://172.16.16.6/',
  'http://cinemacity.live/',
  'http://furiousnet.net/ftp/',
  'http://103.85.160.7/',
  'http://103.49.168.107/',
  'http://ctgoz.com',
  'http://103.219.232.190/',
  'http://akkadukka.com/',
  'http://bdflixlive.com/',
  'http://lalbatte.net/',
  'http://ctgmovies.com/',
  'http://mymoviebazar.net/',
  'http://103.103.239.66/',
  'http://timepassbd.live/',
  'http://mathanosto.top/',
  'http://sunplex.net/',
  'http://103.82.8.194/',
  'http://203.83.177.225/',
  'http://103.222.20.150/',
  'http://103.214.200.94/',
  'http://movieserver.net/',
  'http://tnetftp.com/web/index.html#!/home',
  'http://candybd.net/',
  'http://103.29.127.14/',
  'http://beeflix.biz/',
  'http://timenai.com/',
  'http://movie.smartnetltd.com/',
  'http://146.196.48.10/',
  'http://cdn2.radiantbd.com/',
  'http://mojaloss.stream/',
  'http://10.16.100.244/',
  'http://media.xenialbb.net/',
  'http://103.109.56.114/',
  'http://103.109.56.115/',
  'http://ftp2web.com/',
  'http://halum.net/',
  'http://103.56.6.6/',
  'http://movies.kloud.com.bd/',
  'http://media.dfnbd.net/',
  'http://onnosomoy.com:8096/web/index.html',
  'http://103.135.208.2/',
  'http://103.91.144.230/',
];
